=== piecioshka/test-angular-ajv/src/schemas/movies.scheme.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "$id": "http://example.com/example.json",
    "type": "array",
    "title": "The Root Schema",
    "description": "The root schema comprises the entire JSON document.",
    "default": [],
    "additionalItems": true,
    "items": {
        "$id": "#/items",
        "type": "object",
        "title": "The Items Schema",
        "description": "An explanation about the purpose of this instance.",
        "default": {},
        "additionalProperties": true,
        "required": [
            "id",
            "title",
            "description",
            "thumbUrl",
            "movieUrl"
        ],
        "properties": {
            "id": {
                "$id": "#/items/properties/id",
                "type": "string",
                "title": "The Id Schema",
                "description": "An explanation about the purpose of this instance.",
                "default": "",
                "examples": [
                    "945bbed5-aebe-5ada-829d-2a985ce2e95f"
                ]
            },
            "title": {
                "$id": "#/items/properties/title",
                "type": "string",
                "title": "The Title Schema",
                "description": "An explanation about the purpose of this instance.",
                "default": "",
                "examples": [
                    "ex quis et irure aliquip"
                ]
            },
            "description": {
                "$id": "#/items/properties/description",
                "type": "string",
                "title": "The Description Schema",
                "description": "An explanation about the purpose of this instance.",
                "default": "",
                "examples": [
                    "Zasik joeh catiwu foedare hoju bufufo ugmibal ilwomip tenizte nezsi ihomod bibumof kak zilo fit ga disodabif."
                ]
            },
            "thumbUrl": {
                "$id": "#/items/properties/thumbUrl",
                "type": "string",
                "title": "The Thumb URL Schema",
                "description": "An explanation about the purpose of this instance.",
                "default": "",
                "examples": [
                    "https://picsum.photos/id/7/300/150/"
                ]
            },
            "movieUrl": {
                "$id": "#/items/properties/movieUrl",
                "type": "string",
                "title": "The Movie URL Schema",
                "description": "An explanation about the purpose of this instance.",
                "default": "",
                "examples": [
                    "https://www.youtube.com/watch?v=5cztb819wf"
                ]
            }
        }
    }
}

=== piecioshka/test-angular-ajv/src/fixtures/movies.fixture.json
[
    {
      "id": "945bbed5-aebe-5ada-829d-2a985ce2e95f",
      "title": "ex quis et irure aliquip",
      "description": "Zasik joeh catiwu foedare hoju bufufo ugmibal ilwomip tenizte nezsi ihomod bibumof kak zilo fit ga disodabif.",
      "thumbUrl": "https://picsum.photos/id/7/300/150/",
      "movieUrl": "https://www.youtube.com/watch?v=5cztb819wf"
    },
    {
      "id": "24d77c90-ad63-550a-b7db-2eb563377078",
      "title": "laboris dolor id culpa dolor",
      "description": "Wi he juuj naficgi pom poucu rece biru juod irnufel rulize diacuduk naedibu oleac voewa.",
      "thumbUrl": "https://picsum.photos/id/618/300/150/",
      "movieUrl": "https://www.youtube.com/watch?v=r8r4byouao"
    },
    {
      "id": "b70155e4-c9e6-5790-accb-7ad40c59c3d5",
      "title": "dolor sit",
      "description": "Necvu dijrib co rojin li nael dudulka kuno ve hamafcat tiego peuvva.",
      "thumbUrl": "https://picsum.photos/id/222/300/150/",
      "movieUrl": "https://www.youtube.com/watch?v=az34hej159"
    },
    {
      "id": "f27b7ceb-fb0b-5a33-bf48-853ecdcb86be",
      "title": "est ullamco",
      "description": "Agzi rem covso kaiwa we nalfufse je ho janibit vuw fuebe ru guhepeer ba.",
      "thumbUrl": "https://picsum.photos/id/372/300/150/",
      "movieUrl": "https://www.youtube.com/watch?v=wmrovuu0es"
    },
    {
      "id": "f7cd8560-03e3-5106-a537-6afb19a3a72b",
      "title": "aliqua ad in dolor nostrud",
      "description": "Tiuf ihujodwus woj uzi itu toaf zajufgo eru ro sadmob jeahiupo legohno juz weduh rogko aj op.",
      "thumbUrl": "https://picsum.photos/id/344/300/150/",
      "movieUrl": "https://www.youtube.com/watch?v=vzaffod9a9"
    },
    {
      "id": "15f8c4d7-1f86-516e-ac06-74cf3a5523e2",
      "title": "in est",
      "description": "Ubize eponahfo vowoc cor jes rogfo kuholjel fimaile po ro efberiku zu itbosvur tovok dajcag.",
      "thumbUrl": "https://picsum.photos/id/1037/300/150/",
      "movieUrl": "https://www.youtube.com/watch?v=9o5u9za7v4"
    },
    {
      "id": "b515f936-c1c0-54f9-b4a3-deafcc4cdded",
      "title": "aute",
      "description": "Ultedu falas ucomo oki mon vaga za ju fioceuh godvuj ribep koma ci lowunvok cifsajo.",
      "thumbUrl": "https://picsum.photos/id/918/300/150/",
      "movieUrl": "https://www.youtube.com/watch?v=f6q3yjeat7"
    },
    {
      "id": "852e2139-fd3c-5694-b5a2-bd42139bb6c6",
      "title": "esse in id nostrud",
      "description": "Toijo ciekmu wuwja wi sammo tugnen gaabgaz ginababu nel jerej tonlim jesvolobe pizbedbe tipejo tevnemi encuim.",
      "thumbUrl": "https://picsum.photos/id/391/300/150/",
      "movieUrl": "https://www.youtube.com/watch?v=bnw6ti7m7l"
    },
    {
      "id": "4716ead4-755c-5c13-a4b3-21fa9dab8376",
      "title": "minim",
      "description": "Buhiir cod doto osedepav fojacfub petdijiv epehiv ziure hi kinasek iki lanihi oh pucpizsun raube bofa epuoteemi har.",
      "thumbUrl": "https://picsum.photos/id/691/300/150/",
      "movieUrl": "https://www.youtube.com/watch?v=pbicnb7mla"
    },
    {
      "id": "5f2d5e7a-1494-5d0f-98ca-96378fd4af0f",
      "title": "Duis ea",
      "description": "Nufvudhe bepuga duun sujcu fuecrub bit naldig ir su niot vuesu cuw mozcivuv janap raji giv zemrop aponi.",
      "thumbUrl": "https://picsum.photos/id/305/300/150/",
      "movieUrl": "https://www.youtube.com/watch?v=08s0vmoty9"
    },
    {
      "id": "8bbce0c7-2fbf-5aa0-a1d1-97a1cd2046cc",
      "title": "dolor",
      "description": "Akajoga ohec nulic cac loj ratzan luzogu jolsitwi ingijed wowja apuke ihaebne mog.",
      "thumbUrl": "https://picsum.photos/id/1006/300/150/",
      "movieUrl": "https://www.youtube.com/watch?v=1cwxu0kuyy"
    },
    {
      "id": "ef68da24-b0b6-514a-988c-927dfcce58e7",
      "title": "dolor",
      "description": "Je hifpouco tiba jihu zatgu cenfis ig fujickek bagtah egeweot sico ro getib fopazuuze tiz hajun latidu.",
      "thumbUrl": "https://picsum.photos/id/924/300/150/",
      "movieUrl": "https://www.youtube.com/watch?v=1m7aossdek"
    },
    {
      "id": "22b30b7e-2f98-5e72-8fd6-a30b98a723b4",
      "title": "in eiusmod ullamco consequat",
      "description": "Regzowef zoge nolef kuag zuz lo gejjidic rozgu fetowja geen naja hug tevmeg afotico sa ho fih tas.",
      "thumbUrl": "https://picsum.photos/id/709/300/150/",
      "movieUrl": "https://www.youtube.com/watch?v=31wn1t34zj"
    },
    {
      "id": "12ea7381-5f05-5617-a6f6-460b7477dc0e",
      "title": "proident enim mollit labore commodo",
      "description": "Uthuje mupo hur cibez niajuwo mufacac rudkuvlej fa fezfirnas kucjal se ofutep bepi senfip doflu.",
      "thumbUrl": "https://picsum.photos/id/562/300/150/",
      "movieUrl": "https://www.youtube.com/watch?v=1c42i49fyd"
    },
    {
      "id": "40a35025-8ec0-506d-a662-383c103ec9ef",
      "title": "dolore in Excepteur",
      "description": "Zire ef no zuujo ribhezku hegporje zovoiz soho kaic nemev zeteggi mo zu ges ku akirel hicilti cav.",
      "thumbUrl": "https://picsum.photos/id/12/300/150/",
      "movieUrl": "https://www.youtube.com/watch?v=yctpx3gm47"
    },
    {
      "id": "26a48ed0-50fe-5ae9-96f8-cfa7acc33f5d",
      "title": "laboris anim",
      "description": "Bemuje porpo rep ota enaceil atwu feshi biki koknirroz vecagi zeh jacozsap.",
      "thumbUrl": "https://picsum.photos/id/590/300/150/",
      "movieUrl": "https://www.youtube.com/watch?v=4fa0po00dm"
    },
    {
      "id": "42fc7fea-450e-599d-8958-f3ca0636caca",
      "title": "laborum culpa",
      "description": "Elogatom erfi igru iz ug buc pop lo eweob kiam ahitetoj gaberodel rudibazaf paradun uvi.",
      "thumbUrl": "https://picsum.photos/id/312/300/150/",
      "movieUrl": "https://www.youtube.com/watch?v=pm0d0ecfl5"
    },
    {
      "id": "d2251e2e-0d72-5a90-b18f-7d238c78b2a0",
      "title": "aute officia commodo aliquip tempor",
      "description": "Ip juse vaparocip idsursid potem kezbe iwe rine davko kijakov dih zurlap ewiasi surmisamo pob hechav fit dabfelif.",
      "thumbUrl": "https://picsum.photos/id/246/300/150/",
      "movieUrl": "https://www.youtube.com/watch?v=49y8n4fh83"
    },
    {
      "id": "4093966e-9463-5650-8a8f-a5eb664bdec3",
      "title": "adipisicing Lorem laboris consectetur",
      "description": "Rasoluj bucesdoj icu me haj zegeka id lihabem vof urwur mijsihwe et tezi elo sazzeke no.",
      "thumbUrl": "https://picsum.photos/id/127/300/150/",
      "movieUrl": "https://www.youtube.com/watch?v=7hspicjoxu"
    },
    {
      "id": "d0c80440-37fe-55f0-9856-b734a239a551",
      "title": "occaecat",
      "description": "Wewu dihlatpa nosu ne dir gav oheuhiom fochawko ij vojloh gug bodoruhip mi virkujce mi mem odapuni.",
      "thumbUrl": "https://picsum.photos/id/74/300/150/",
      "movieUrl": "https://www.youtube.com/watch?v=yar8tv43w4"
    },
    {
      "id": "2c73d217-9019-5fd8-90c3-64ca522a71d9",
      "title": "aliquip minim commodo fugiat laborum",
      "description": "Fum rideh nehepru faaso savezoc mi hod pujwiune gezuz go fesur wojlamohi jepneh.",
      "thumbUrl": "https://picsum.photos/id/392/300/150/",
      "movieUrl": "https://www.youtube.com/watch?v=k3dwf91tvw"
    },
    {
      "id": "51ea0c82-9483-5484-a1aa-8f96730f6efa",
      "title": "exercitation Ut",
      "description": "Octo netiofe egani imizo biwior ow nu sab inabuhvo gat nokek dub cir cazatpe iduco ko.",
      "thumbUrl": "https://picsum.photos/id/811/300/150/",
      "movieUrl": "https://www.youtube.com/watch?v=u29zizjme8"
    }
  ]
